# Use tech_user/secret as user/password credentials
version: '3'

services:
  db-ref:
    image: postgres:10.3
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: migrationTestDb_18
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == database-ref
    command:
      - -c
      - max_connections=200
      - -c
      - max_prepared_transactions=200
  db-from:
    image: postgres:10.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: migrationTestDb_18
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == database
          - node.labels.stack_name == from
    depends_on:
      - db-ref
    command:
      - -c
      - max_connections=200
      - -c
      - max_prepared_transactions=200

  bonita-from:
    hostname: bonita
    image: bonitasoft/bonita-subscription:7.4.3-fdw
    ports:
      - 8080:8080
    volumes:
       - /home/ubuntu/lic/:/opt/bonita_lic
       - /home/ubuntu/custom-init.d:/opt/custom-init.d
    environment:
      - POSTGRES_ENV_POSTGRES_PASSWORD=migrationTestDb_18
      - DB_VENDOR=postgres
      - DB_HOST=db-from
      - DB_ADMIN_USER=postgres
      - DB_ADMIN_PASS=migrationTestDb_18
      - DB_NAME=bonitadb
      - DB_USER=bonitauser
      - DB_PASS=migrationTestDb_18
      - TENANT_LOGIN=install
      - TENANT_PASSWORD=install
      - PLATFORM_LOGIN=platformAdmin
      - PLATFORM_PASSWORD=platform
      - REPOSITORY_HOST=db-ref
      - REPOSITORY_PORT=5432
      - REPOSITORY_NAME=postgres
      - REPOSITORY_USER=postgres
      - REPOSITORY_PASS=migrationTestDb_18
      - WORKER_COREPOOLSIZE=100
      - WORKER_MAXPOOLSIZE=100 
      - SCHEDULER_POOLSIZE=10
      - SCHEDULER_BATCHSIZE=1000
      - DS1_MINPOOLSIZE=1
#workermaxpoolsize*2 + scheduler_poolsize
      - DS1_MAXPOOLSIZE=150 
      - DS2_MINPOOLSIZE=1
      - DS2_MAXPOOLSIZE=20
      - MAX_THREADS=200
    restart: on-failure:5
    deploy:
      placement:
        constraints:
          - node.labels.type == bonita
          - node.labels.stack_name == from
    depends_on:
      - db-from
      - db-ref
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Waiting for Postgres to be available'
        export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
        maxTries=10
        while [ "$$maxTries" -gt 0 ] && ! psql -h "$$DB_HOST" -U 'postgres' -c '\l'; do
            let maxTries--
            sleep 1
        done
        echo
        if [ "$$maxTries" -le 0 ]; then
            echo >&2 'error: unable to contact Postgres after 10 tries'
            exit 1
        fi
        exec /opt/files/startup.sh

  db-to:
    image: postgres:10.3
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: migrationTestDb_18
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == database
          - node.labels.stack_name == to
    depends_on:
      - db-ref
    command:
      - -c
      - max_connections=200
      - -c
      - max_prepared_transactions=200

  bonita-to:
    hostname: bonita
    image: bonitasoft/bonita-subscription:7.4.3-fdw
    ports:
      - 8081:8080
    volumes:
       - /home/ubuntu/lic/:/opt/bonita_lic
       - /home/ubuntu/custom-init.d:/opt/custom-init.d
    environment:
      - POSTGRES_ENV_POSTGRES_PASSWORD=migrationTestDb_18
      - DB_VENDOR=postgres
      - DB_HOST=db-to
      - DB_ADMIN_USER=postgres
      - DB_ADMIN_PASS=migrationTestDb_18
      - DB_NAME=bonitadb
      - DB_USER=bonitauser
      - DB_PASS=migrationTestDb_18
      - TENANT_LOGIN=install
      - TENANT_PASSWORD=install
      - PLATFORM_LOGIN=platformAdmin
      - PLATFORM_PASSWORD=platform
      - REPOSITORY_HOST=db-ref
      - REPOSITORY_PORT=5432
      - REPOSITORY_NAME=postgres
      - REPOSITORY_USER=postgres
      - REPOSITORY_PASS=migrationTestDb_18
      - WORKER_COREPOOLSIZE=100
      - WORKER_MAXPOOLSIZE=100 
      - SCHEDULER_POOLSIZE=10
      - SCHEDULER_BATCHSIZE=1000
      - DS1_MINPOOLSIZE=1
#workermaxpoolsize*2 + scheduler_poolsize
      - DS1_MAXPOOLSIZE=150 
      - DS2_MINPOOLSIZE=1
      - DS2_MAXPOOLSIZE=20
      - MAX_THREADS=200
    restart: on-failure:5
    deploy:
      placement:
        constraints:
          - node.labels.type == bonita
          - node.labels.stack_name == to
    depends_on:
      - db-ref
      - db-to
      - bonita-from
    entrypoint:
      - bash
      - -c
      - |
        set -e
        sleep 30
        echo 'Waiting for Postgres to be available'
        export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
        maxTries=10
        while [ "$$maxTries" -gt 0 ] && ! psql -h "$$DB_HOST" -U 'postgres' -c '\l'; do
            let maxTries--
            sleep 1
        done
        echo
        if [ "$$maxTries" -le 0 ]; then
            echo >&2 'error: unable to contact Postgres after 10 tries'
            exit 1
        fi
        exec /opt/files/startup.sh
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db-ref
      - db-from
      - db-to
      - bonita-from
      - bonita-to
    command: db-ref:5432 db-from:5432 db-to:5432 bonita-from:8080 bonita-to:8080
                
